# Generated by Django 4.2 on 2024-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_electrica_anio_electrica_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acustica',
            name='anio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acustica',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='acustica',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acustica',
            name='serial',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='amplificador',
            name='anio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='amplificador',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='amplificador',
            name='potencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='amplificador',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='amplificador',
            name='serial',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='efecto',
            name='anio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='efecto',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='efecto',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='efecto',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
