# Generated by Django 4.2 on 2024-08-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acustica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.IntegerField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('precio', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amplificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('potencia', models.IntegerField(null=True)),
                ('serial', models.IntegerField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('precio', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Efecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.IntegerField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('precio', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.IntegerField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('precio', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
