# Generated by Django 4.2.1 on 2024-08-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrica',
            name='imagen',
            field=models.ImageField(default='hola', upload_to='media/'),
            preserve_default=False,
        ),
    ]
