# Generated by Django 4.2.1 on 2024-08-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbc', '0002_electrica_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='acustica',
            name='imagen',
            field=models.ImageField(default='dasdasd', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amplificador',
            name='imagen',
            field=models.ImageField(default='sasdasd', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efecto',
            name='imagen',
            field=models.ImageField(default='asasa', upload_to='media/'),
            preserve_default=False,
        ),
    ]
