# Generated by Django 4.2.1 on 2024-08-14 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vbc', '0004_acustica_creado_por_acustica_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrica',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
