# Generated by Django 4.2 on 2024-08-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbc', '0002_acustica_email_contacto_amplificador_email_contacto_and_more'),
        ('vbc', '0007_alter_acustica_creado_por_and_more'),
    ]

    operations = [
    ]
